### ISSUE TITLE
'ready' event is not really ready

### ISSUE THREAD

**Issue by ckt1010** [agebrock/reverse-tunnel-ssh#3]
Hi,
I found 'ready' event is emit as soon as it connect to reverse server, but forward and something else need to do after that.
So if I connect to this client after it receive 'ready' event too fast, it will receive ECONNREFUSED.
I think maybe you should add a new event or some better way to fix
Thanks a lot!

**Comment by agebrock** [comment]
Will be fixed with the current release and the "forward-in" event.

**Comment by agebrock** [comment]
Let me know if that release fixed your problem. 

Thx
